#!/usr/bin/env bash
# ============================================================
# OpenClaw One-Click Deploy Script
# ============================================================
#
# Deploys an OpenClaw agent container using:
#   - A standard docker-compose.yml (never modified)
#   - A .env file generated from user input
#
# Usage:
#   chmod +x deploy.sh && ./deploy.sh
#
# What this script does:
#   1. Checks/installs Docker + Docker Compose
#   2. Auto-generates PORT and GATEWAY_TOKEN
#   3. Prompts for API keys (OpenRouter required, others optional)
#   4. Writes .env
#   5. Runs docker compose up -d
#   6. Prints connection info
#
# Requirements:
#   - Ubuntu 22.04+ / Debian 12+ (or any Docker-compatible Linux)
#   - Root or sudo access
#   - At least 2GB RAM, 10GB disk
#
# ============================================================

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

log()   { echo -e "${GREEN}[✓]${NC} $1"; }
warn()  { echo -e "${YELLOW}[!]${NC} $1"; }
err()   { echo -e "${RED}[✗]${NC} $1"; exit 1; }
info()  { echo -e "${CYAN}[i]${NC} $1"; }

echo ""
echo -e "${BOLD}╔══════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║       OpenClaw Agent — One-Click Deploy         ║${NC}"
echo -e "${BOLD}╚══════════════════════════════════════════════════╝${NC}"
echo ""

# ── Step 1: Check / Install Docker ─────────────────────────
info "Checking Docker installation..."

if command -v docker &> /dev/null; then
    log "Docker found: $(docker --version)"
else
    warn "Docker not found. Installing..."
    curl -fsSL https://get.docker.com | sh
    systemctl enable docker
    systemctl start docker
    log "Docker installed: $(docker --version)"
fi

if docker compose version &> /dev/null; then
    log "Docker Compose found: $(docker compose version --short)"
else
    err "Docker Compose plugin not found. Please install it: https://docs.docker.com/compose/install/"
fi

# ── Step 2: Set up deploy directory ────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPLOY_DIR="${DEPLOY_DIR:-$SCRIPT_DIR}"

# Ensure docker-compose.yml exists
if [ ! -f "$DEPLOY_DIR/docker-compose.yml" ]; then
    err "docker-compose.yml not found in $DEPLOY_DIR. Run this script from the project root."
fi

cd "$DEPLOY_DIR"

# Create persistent dirs
mkdir -p config workspace
log "Deploy directory: $DEPLOY_DIR"

# ── Step 3: Auto-generate PORT and TOKEN ───────────────────
info "Generating secure credentials..."

PORT=$(shuf -i 10000-65000 -n 1)
GATEWAY_TOKEN=$(openssl rand -hex 16)

log "Port: $PORT"
log "Gateway token generated"

# ── Step 4: Prompt for API keys ───────────────────────────
echo ""
echo -e "${BOLD}── API Keys ──${NC}"
echo ""

# Mandatory: OpenRouter
read -p "$(echo -e "${CYAN}[REQUIRED]${NC} OpenRouter API key (sk-or-v1-...): ")" OPENROUTER_KEY
if [ -z "$OPENROUTER_KEY" ]; then
    err "OpenRouter API key is required. Get one at https://openrouter.ai/keys"
fi
log "OpenRouter key set"

# Optional: Anthropic
read -p "$(echo -e "${YELLOW}[OPTIONAL]${NC} Anthropic API key (Enter to skip): ")" ANTHROPIC_KEY
[ -n "$ANTHROPIC_KEY" ] && log "Anthropic key set" || info "Skipped Anthropic"

# Optional: OpenAI
read -p "$(echo -e "${YELLOW}[OPTIONAL]${NC} OpenAI API key (Enter to skip): ")" OPENAI_KEY
[ -n "$OPENAI_KEY" ] && log "OpenAI key set" || info "Skipped OpenAI"

echo ""
echo -e "${BOLD}── Integrations ──${NC}"
echo ""

# Optional: Telegram
read -p "$(echo -e "${YELLOW}[OPTIONAL]${NC} Telegram Bot Token (Enter to skip): ")" TELEGRAM_TOKEN
TELEGRAM_UID=""
if [ -n "$TELEGRAM_TOKEN" ]; then
    read -p "$(echo -e "${CYAN}[REQUIRED]${NC} Telegram User ID: ")" TELEGRAM_UID
    if [ -z "$TELEGRAM_UID" ]; then
        err "Telegram User ID is required when Bot Token is set"
    fi
    log "Telegram configured"
else
    info "Skipped Telegram"
fi

# Optional: WhatsApp
read -p "$(echo -e "${YELLOW}[OPTIONAL]${NC} WhatsApp number (+1234567890, Enter to skip): ")" WHATSAPP_NUM
[ -n "$WHATSAPP_NUM" ] && log "WhatsApp configured" || info "Skipped WhatsApp"

# ── Step 5: Write .env ───────────────────────────────────
info "Writing .env..."

if [ -f .env ]; then
    cp .env ".env.backup.$(date +%s)"
    warn "Existing .env backed up"
fi

cat > .env << EOF
# Auto-generated by deploy.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# [AUTO] Auto-generated
PORT=${PORT}
OPENCLAW_GATEWAY_TOKEN=${GATEWAY_TOKEN}

# [MANDATORY] LLM
OPENROUTER_API_KEY=${OPENROUTER_KEY}

# [OPTIONAL] Additional LLM providers
ANTHROPIC_API_KEY=${ANTHROPIC_KEY:-}
OPENAI_API_KEY=${OPENAI_KEY:-}

# [OPTIONAL] Telegram
TELEGRAM_BOT_TOKEN=${TELEGRAM_TOKEN:-}
TELEGRAM_USER_ID=${TELEGRAM_UID:-}

# [OPTIONAL] WhatsApp
WHATSAPP_NUMBER=${WHATSAPP_NUM:-}
EOF

log ".env written"

# ── Step 6: Launch container ─────────────────────────────
echo ""
info "Launching OpenClaw container..."
docker compose up -d

# Wait for startup
info "Waiting for container to start..."
sleep 8

if docker compose ps | grep -q "running"; then
    log "Container is running!"
else
    warn "Container may not be ready yet. Check: docker compose logs -f"
fi

# ── Step 7: Print connection info ────────────────────────
SERVER_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "YOUR_SERVER_IP")

echo ""
echo -e "${BOLD}╔══════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║           Deployment Complete! 🚀                ║${NC}"
echo -e "${BOLD}╚══════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${CYAN}Gateway URL:${NC}      ws://${SERVER_IP}:${PORT}"
echo -e "  ${CYAN}Gateway Token:${NC}    ${GATEWAY_TOKEN}"
echo -e "  ${CYAN}Port:${NC}             ${PORT}"
echo -e "  ${CYAN}Deploy Dir:${NC}       ${DEPLOY_DIR}"
echo ""
echo -e "  ${BOLD}Quick Commands:${NC}"
echo -e "    View logs:    ${YELLOW}docker compose logs -f${NC}"
echo -e "    Stop:         ${YELLOW}docker compose down${NC}"
echo -e "    Restart:      ${YELLOW}docker compose restart${NC}"
echo -e "    Redeploy:     ${YELLOW}docker compose down && docker compose up -d${NC}"
echo ""
echo -e "  ${BOLD}Connect from Aether UI:${NC}"
echo -e "    1. Go to Settings → Remote Config"
echo -e "    2. URL:   ${CYAN}ws://${SERVER_IP}:${PORT}${NC}"
echo -e "    3. Token: ${CYAN}${GATEWAY_TOKEN}${NC}"
echo ""
echo -e "  ${BOLD}SSH Tunnel (if port not exposed):${NC}"
echo -e "    ${YELLOW}ssh -N -L ${PORT}:127.0.0.1:${PORT} root@${SERVER_IP}${NC}"
echo ""
